

PARAM_REQUIRED = "PARAM_REQUIRED"
FIELD_REQUIRED = "FIELD_REQUIRED"
UNKNOWN_VALUE = "UNKNOWN_VALUE"
UNKNOWN_RESOURCE = "UNKNOWN_RESOURCE"
BAD_MATERIAL_PRODUCT = "BAD_MATERIAL_PRODUCT"
BAD_FINAL_PRODUCT = "BAD_FINAL_PRODUCT"
BAD_EQUIVALENCE_PARAM = "BAD_EQUIVALENCE_PARAM"
NO_STOCK = "NO_STOCK"
NOT_ENOUGH_STOCK = "NOT_ENOUGH_STOCK"
CANNOT_DELIVER_MATERIAL_PRODUCT = "CANNOT_DELIVER_MATERIAL_PRODUCT"
NOT_A_MANUFACTOR = "NOT_A_MANUFACTOR"
UNKNOWN_ORGANISATION = "UNKNOWN_ORGANISATION"
DELIVERYITEM_ALREADY_EXPORTED = "DELIVERYITEM_ALREADY_EXPORTED"

ERROR_MESSAGES = {
    PARAM_REQUIRED: "{} is required",
    FIELD_REQUIRED: "{} of {} is required",
    UNKNOWN_VALUE: "Value {} is unknown for the field {}",
    UNKNOWN_RESOURCE: "Unknown ressource",
    BAD_MATERIAL_PRODUCT: "{} is not a material product.",
    BAD_FINAL_PRODUCT: "{} is not a final product.",
    BAD_EQUIVALENCE_PARAM: "{} argument: Missing field {}.",
    NO_STOCK: "No stock for reference {}",
    NOT_ENOUGH_STOCK: "Not enough stock for reference {}",
    CANNOT_DELIVER_MATERIAL_PRODUCT: "Cannot deliver material product",
    NOT_A_MANUFACTOR: "{} is not a manufactor",
    UNKNOWN_ORGANISATION: "{} is an unknown orgagnisation",
    DELIVERYITEM_ALREADY_EXPORTED: "Delivery item {}-{} has been already exported."
}


