"""empty message

Revision ID: 2f3f5897d2
Revises: 1f290ce16e8
Create Date: 2020-03-26 22:27:44.206383

"""

# revision identifiers, used by Alembic.
revision = '2f3f5897d2'
down_revision = '1f290ce16e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orga_organization', sa.Column('vid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'orga_organization', ['vid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orga_organization', type_='unique')
    op.drop_column('orga_organization', 'vid')
    ### end Alembic commands ###
