"""empty message

Revision ID: 4ddf2ddee3a
Revises: 2f3f5897d2
Create Date: 2020-04-09 09:39:47.692109

"""

# revision identifiers, used by Alembic.
revision = '4ddf2ddee3a'
down_revision = '2f3f5897d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=25), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('product_equivalence',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['product_product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'material_id')
    )
    op.create_table('product_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('transporter_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['orga_organization.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['orga_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_deliveryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('manufactor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufactor_id'], ['orga_organization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_deliveryitem_batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('deliveryitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batch.id'], ),
    sa.ForeignKeyConstraint(['deliveryitem_id'], ['product_deliveryitem.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'deliveryitem_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_deliveryitem_batch')
    op.drop_table('product_deliveryitem')
    op.drop_table('product_batch')
    op.drop_table('product_stock')
    op.drop_table('product_equivalence')
    op.drop_table('product_product')
    ### end Alembic commands ###
